project:
  type: website
  output-dir: docs # to publish website on GithubPages
# --- By default, all valid Quarto input files (.qmd, .ipynb, .md, .Rmd)
#  will be rendered (NO .file, _dir/)
  render:
    - "*.qmd"
    - "!secret/"
    - "!zzz_old_distill/"
    - "!posts/"
    # - "!writings/"
    - "!talks/"

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Luisa Maria Mimmi"
  description: "Personal website and consulting page"
  site-url: "{{< var website.site-url >}}" # "https://lulliter.github.io/nerd-help"
  # Account Google Mktg "Lulliter github (UA-128632724)" collegato a luisamimmi.org
  google-analytics: "UA-128632724"
  favicon: images/favicon_init32.png # https://favicon.io/favicon-generator/
  search: false # no magnifier on navbar
  page-navigation: true

  page-footer:
    left: |
      {{< fa regular copyright >}} Luisa M. Mimmi 2024
# left: |
#   {{< fa brands creative-commons >}} 2024 Luisa M. Mimmi <br>
#   License {{< fa brands creative-commons >}}
#   {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}
#   [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) | [Source code at {{< fa brands github >}}](https://github.com/Lulliter/luisamimmi)
    background: "#BDD5E1" #"#e7d8da" #"#e3eff7"

  navbar:
#    logo: images/MITGEST_logo.jpeg
    pinned: true # non si muove quando scorro la pagina
    background: "#3881a5" # "#23749b" # "#b78a92" # "#72aed8" # "#0084e6" "#EE6A24"
    right:
      - text: "Home"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.html
      # - text: "Blog"
      #   icon: cup-hot-fill # archive-fill # https://icons.getbootstrap.com/?q=home
      #   href: posts/index.qmd
      # - text: "Portfolio"
      #   icon: terminal-fill #  archive-fill # https://icons.getbootstrap.com/?q=home
      #   href: portfolio
      - text: "Research & writing"
        icon: cup-hot-fill # archive-fill # https://icons.getbootstrap.com/?q=home
        href: writings/index.qmd
      - text: "{{< fa brands r-project >}} Projects"
#        icon: "{{< fa brands r-project >}}" # terminal-fill #mortarboard-fill # https://icons.getbootstrap.com/?q=home
        href: projects/index.qmd

format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1rem
    theme: theme/Lulas_theme.scss
    # css: theme/styles.css
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"
#  reduce / DELETE SIDEBAR SPACE
    grid:
      body-width: 2000px
      sidebar-width: 150px # non mi serve perche non c'e'
      margin-width: 300px


